name: Update BLS Data

on:
  schedule:
    - cron: '0 0 1 * *'  # Run on the 1st of each month
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch and Process Data
        run: |
          python scripts/data_collection.py
          python scripts/data_processing.py

      - name: Commit and Push Updated Data
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add data/
          git commit -m "Automated data update"
          git push
